---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config-v1
  namespace: media
  # labels:
  #   kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
