# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: downloads
type: Opaque
stringData:
    SABNZBD__API_KEY: "${SECRET_SABNZBD__API_KEY}"
    SABNZBD__NZB_KEY: "${SECRET_SABNZBD__NZB_KEY}"
