---
kubernetes:
  children:
    master:
      hosts:
        apk3s00:
          ansible_host: 10.50.50.30
        apk3s01:
          ansible_host: 10.50.50.31
        apk3s02:
          ansible_host: 10.50.50.32
    worker:
      hosts:
        aprp04:
          ansible_host: 10.50.50.104
        aprp05:
          ansible_host: 10.50.50.105
        aprp06:
          ansible_host: 10.50.50.106
        aprp07:
          ansible_host: 10.50.50.107
        aprp08:
          ansible_host: 10.50.50.108
        aprp09:
          ansible_host: 10.50.50.109
        aprp10:
          ansible_host: 10.50.50.110
        aprp11:
          ansible_host: 10.50.50.111
        aprp12:
          ansible_host: 10.50.50.112
        apk3s14:
          ansible_host: 10.50.50.44
        apk3s11:
          ansible_host: 10.50.50.41
        apk3s12:
          ansible_host: 10.50.50.42
        aprp01:
          ansible_host: 10.50.50.101
        aprp02:
          ansible_host: 10.50.50.102
        aprp03:
          ansible_host: 10.50.50.103
