---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - bazarr
  # - doplarr
  - lidarr
  - overseerr
  - prowlarr
  - qbittorrent
  - radarr
  # - radarr-uhd
  - readarr
  - sabnzbd
  - sonarr
  # - sonarr-uhd
  - ./namespace.yaml
