---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.4
    hostname: qbittorrent
    podAnnotations:
      setGateway: "true"
    env:
      TZ: ${TIMEZONE}
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__BT_PORT: &port-bt "${SECRET_VPN_FORWARDED_PORT_1}"
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: qbittorrent.png
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent.downloads.svc.cluster.local:8080
          gethomepage.dev/widget.username: "${HOMEPAGE_VAR_QBITTORRENT_USERNAME}"
          gethomepage.dev/widget.password: "${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}"
        hosts:
          - host: &host "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: "${SECRET_UID}"
      runAsGroup: "${SECRET_GID}"
      fsUser: "${SECRET_FS_UID}"
      fsGroup: "${SECRET_FS_GID}"
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 5010
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /Shares/Files/
            fsGroup: "${SECRET_FS_GID}"
            fsUser: "${SECRET_FS_UID}"
        mountPath: /Files
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 6000Mi
