---
- Communitcate:
    - Discord:
        - icon: discord.png
          href: 'https://discord.com/app'
    - Gmail:
        - icon: gmail.png
          href: 'http://gmail.com'
    - Google Calendar:
        - icon: google-calendar.png
          href: 'https://calendar.google.com'
    - Outlook:
        - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/outlook.png
          href: 'https://outlook.com'
- Media:
    - YouTube:
        - icon: youtube.png
          href: 'https://youtube.com/feed/subscriptions'
    - Spotify:
        - icon: spotify.png
          href: 'http://open.spotify.com'
    - Youtube Music:
        - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/youtube-music.png
          href: 'https://music.youtube.com'
- Reading:
    - Beyond:
        - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/beyond.png
          href: 'https://forums.beyond.ca/search.php?do=getnew&contenttype=vBForum_Post'
    - Western Subaru Club:
        - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/wsc.png
          href: 'http://westernsubaruclub.com/smf/index.php?action=unread'
    - Reddit:
        - icon: reddit.png
          href: 'https://reddit.com'
- Git:
    - k8s-at-home:
        - icon: kubernetes-dashboard.png
          href: 'https://nanne.dev/k8s-at-home-search/'
    - k3s-home-cluster:
        - icon: github.png
          href: 'https://github.com/LilDrunkenSmurf/k3s-home-cluster'
