---
- Media:
    - Plex:
        href: https://plex.${SECRET_DOMAIN}
        icon: plex.png
        widget:
          type: plex
          url: http://plex.media.svc.cluster.local:32400
          key: "${HOMEPAGE_VAR_PLEX_TOKEN}"
    # - Tautulli:
    #     href: https://tautulli.${SECRET_DOMAIN}
    #     icon: tautulli.png
    #     widget:
    #       type: tautulli
    #       url: https://tautulli.${SECRET_DOMAIN}
    #       key: {{HOMEPAGE_VAR_TAUTULLI_TOKEN}}
    # - Tdarr:
    #     href: https://tdarr.${SECRET_DOMAIN}
    #     icon: tdarr.png
    #     widget:
    #       type: tdarr
    #       url: http://${NAS_IP}:8265
- Infrastructure:
    # - Unraid:
    #     href: https://nas.${SECRET_DOMAIN}
    #     icon: unraid.png
    #     description: Unraid WebUI
    # - Unifi:
    #     href: https://unifi.ui.com
    #     icon: unifi.png
    #     description: Unifi Dashboard
    #     widget:
    #       type: unifi
    #       url: https://${UNIFI_IP}
    #       username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
    #       password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - PiHole:
        href: http://${PI_IP}
        icon: pi-hole.png
        description: Pi Hole
        widget:
          type: pihole
          url: http://${PI_IP}/admin
          key: "${HOMEPAGE_VAR_PIHOLE_TOKEN}"
    # - Portainer:
    #     href: https://portainer.${SECRET_DOMAIN}
    #     icon: portainer.png
    #     description: Portainer Unraid
    #     widget:
    #       type: portainer
    #       url: http://${DOCKER_IP}:9000
    #       env: 1
    #       key: {{HOMEPAGE_VAR_PORTAINER_TOKEN}}
# - Minecraft:
#     - Vibecraft:
#         icon: minecraft.png
#         server: smurf-raid
#         container: vibecraft
#         widget:
#           type: minecraft
#           url: udp://${NAS_IP}:25565
#     - Skyblock:
#         icon: minecraft.png
#         widget:
#           type: minecraft
#           url: udp://${NAS_IP}:25566
#     - Create:
#         icon: minecraft.png
#         widget:
#           type: minecraft
#           url: udp://${NAS_IP}:25567
