---
title: Dashboard
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
theme: dark
color: slate
headerStyle: clean
layout:
  Media:
    style: row
    columns: 3
    icon: mdi-play-circle
  Infrastructure:
    style: row
    columns: 3
    icon: mdi-harddisk
  Home:
    style: column
    rows: 2
    icon: mdi-home-analytics
  Monitoring:
    style: column
    rows: 2
    icon: mdi-chart-line
  Minecraft:
    style: row
    columns: 3
    icon: mdi-minecraft
  Downloads:
    style: row
    columns: 3
    icon: mdi-download-circle
providers:
  longhorn:
    url: http://longhorn-frontend.storage
