---
# - resources:
#     backend: kubernetes
#     cpu: true
#     expanded: true
#     memory: truehttps://github.com/walkxcode/dashboard-icons/blob/main/png/homepage.png?raw=true
- logo:
    icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/lds-transparent.png
- search:
    provider: [duckduckgo, google]
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: "Howdy Hey!"
- kubernetes:
    cluster:
      cpu: true
      label: cluster
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- openmeteo:
    label: Home
    latitude: ${LATITUDE}
    longitude: ${LONGITUDE}
    units: metric
    cache: 5
- longhorn:
    expanded: false
    total: true
    labels: true
    nodes: false
- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
