apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:rsmiSHJQvcMS4l5zJCrhKpn9/NxMQ+JF7CmV1ZL+SftQ+B25IQ==,iv:ZJiXEFxiuRP2N5woA94K/dEqPUXFdGty2fI0WVVsJqw=,tag:3h1kzShY2DAgAUoTtG4j/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUdXR0h5VGRGS3ZuMXdF
            NXVxZzJCbVBld21yRGpQaVRoYW91U0FURmdNCnkrNXp4QUd0YUVGME5Fc2hnWHhi
            UDA0UDFISFdGYTJSc043Z2M5KzlDeDAKLS0tIEhvM2FxTVVpTFM5bXpMeDYrazMx
            eXN2N0ZnRDhWR3h5cEdDOCsxa1NTZTgKaZFZ54ZnT8JK5gENbyNZWXLryqT0M8Hn
            YWnYGUN7IDWWGkrKv2lHOE1caPAvx1Wz/DJ6FB90pKnnMHxrDiwAdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T05:52:16Z"
    mac: ENC[AES256_GCM,data:CoPQaRDeHUFhhgaXdKKxVPoA1BVdJETolESXY8fTfoLJ0QXGYtri7bJFl+iKNDbX3A92hfbDKPbecT5i7/zxBNU7bCccGb8HXk6+Ewc2jDRxlO0bmoQzTbmBpO2MvKzp6QccsKPFaPD7zlbc2hWYzjNBEOPrujMSP301Nb5HD40=,iv:oTfKRBv+FaIzqP5pcdctP5xvxMjdRE1qnQkqZAZFvwY=,tag:Zs8sV3E7pZ0tVMQqshHjKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
