---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-v1
  namespace: files
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
  storageClassName: rook-ceph-block
