---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: files
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 3.5.20
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # values:
  #   image:
  #     repository: ghcr.io/linuxserver/nextcloud
  #     tag: 27.0.1
    env:
      TZ: "America/Los_Angeles"
      NEXTCLOUD__INSTANCE_NAME: NextCloud
      NEXTCLOUD__PORT: &port 80
      NEXTCLOUD__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        # gethomepage.dev/enabled: "true"
        # gethomepage.dev/icon: nextcloud.png
        # gethomepage.dev/name: NextCloud
        # gethomepage.dev/group: Files
        # gethomepage.dev/widget.type: nextcloud
        # gethomepage.dev/widget.url: http://nextcloud.files.svc.cluster.local
        # gethomepage.dev/widget.key: "${HOMEPAGE_VAR_NEXTCLOUD_TOKEN}"
      hosts:
        - host: "nextcloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "nextcloud.${SECRET_DOMAIN}"
      secretName: nextcloud
    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
      # username: "${SECRET_NEXTCLOUD_USERNAME}"
      password: "${SECRET_NEXTCLOUD_PASSWORD}"
      mail:
        enabled: true
        domain: "${SECRET_DOMAIN}"
        smtp:
          host: "smtp.sendgrid.net"
          secure: ssl
          authtype: LOGIN
      extraVolumes:
        - name: nfs-files
          nfs:
            server: "${NAS_ADDR}"
            path: /Shares/Files/
            readOnly: true
      extraVolumeMounts:
        - name: nfs-files
          mountPath: /mnt/Files
      extraEnv:
      # overwriteprotocol: https
      # overwrite.cli.url: "nextcloud.${SECRET_DOMAIN}"
    podSecurityContext:
      runAsUser: "${SECRET_UID}"
      runAsGroup: "${SECRET_GID}"
      supplementalGroups:
        - 100
    persistence:
      enabled: true
      existingClaim: nextcloud-config-v1
      size: 10Gi
      nextcloudData:
        enabled: true
        # storageClass: rook-ceph-block
        existingClaim: nextcloud-data-v1
        # accessMode: ReadWriteMany
        # size: 1000Gi
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/custom-intel-gpu
    #               operator: In
    #               values:
    #                 - "true"
    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: "nextcloud-promtail"
    resources:
      requests:
        cpu: 2000m
        memory: 1000Mi
      limits:
        memory: 8000Mi
