---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/benphelps/homepage
      tag: nightly
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: homepage-config
        subPath:
          - path: bookmarks.yaml
            mountPath: /app/config/bookmarks.yaml
          - path: docker.yaml
            mountPath: /app/config/docker.yaml
          - path: kubernetes.yaml
            mountPath: /app/config/kubernetes.yaml
          - path: services.yaml
            mountPath: /app/config/services.yaml
          - path: settings.yaml
            mountPath: /app/config/settings.yaml
          - path: widgets.yaml
            mountPath: /app/config/widgets.yaml
    serviceAccount:
      create: true
    resources:
      requests:
        cpu: 15m
        memory: 200M
      limits:
        memory: 400M
    # envFrom:
    #   - secretRef:
    #       name: homepage-secret
