---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.7.1.7640
    env:
      TZ: "America/Los_Angeles"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 80
      RADARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/name: Radarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: http://radarr.downloads.svc.cluster.local
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_RADARR_TOKEN}}"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: "${SECRET_UID}"
      runAsGroup: "${SECRET_GID}"
      fsGroup: "${SECRET_FS_GID}"
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     interval: 3m
    #     scrapeTimeout: 1m
    #   prometheusRule:
    #     enabled: true
    #   exporter:
    #     image:
    #       repository: ghcr.io/onedr0p/exportarr
    #       tag: v0.6.2
    #     env:
    #       port: 9794
    #       additionalMetrics: true
    #       unknownQueueItems: false
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /Shares/Files/
            fsGroup: "${SECRET_FS_GID}"
        mountPath: /Files
    resources:
      requests:
        memory: 500Mi
        cpu: 1000m
      limits:
        memory: 1500Mi
