---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-v1
  namespace: downloads
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-block
